version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    networks:
      - iot_internal
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - iot_internal
    ports:
      - "8083:8083"
      - "8090:8090"
    volumes:
      - ./influxdb/data:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    networks:
      - iot_internal
  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: fatcloud-windrose-panel
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.graphana.rule=Host(`graphana.vatoth.dev`)"
      - "traefik.http.routers.graphana.entrypoints=https"
      - "traefik.http.routers.graphana.tls.certresolver=letsencrypt"
      #- "traefik.http.services.graphana.loadbalancer.server.port=8086"
      - "traefik.docker.network=proxy"

networks:
  iot_internal:
  proxy:
    external: true

volumes:
  db_data: {}
